### ISSUE TITLE
Timeline is very long to be displayed

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#253] opened 2016-03-02 12:27 UTC
The Timeline take more then 10/15s to display ~70 devices.
With the same devices  don't have this probleme before 2 weeks.
Same problem on a VM (1 cpu  i5-4570 CPU @ 3.20GHz / 1Go)  with the same response time and a RPI2 (same devices en VM and rpi2).

I only see the mq time-out in log:

    admin.log
    2016-03-01 16:41:43,871 domogik.admin.application INFO http request for /timeline/ received
    2016-03-01 16:41:45,229 domogik-admin DEBUG Send client status : alive
    2016-03-01 16:42:00,230 domogik-admin DEBUG Send client status : alive
    2016-03-01 16:42:09,088 domogik.admin.application DEBUG  => response status code: 200
    2016-03-01 16:42:09,088 domogik.admin.application DEBUG  => response content_type: text/html; charset=utf-8
    2016-03-01 16:42:15,432 domogik-admin DEBUG Send client status : alive

    broquer.log
    2016-03-01 16:41:43,874 domogik-mq_broker DEBUG Client REQ received: to='manager' data=['datatype.get', '{}']
    2016-03-01 16:41:43,876 domogik-mq_broker DEBUG WORKER REP received: from='manager' data=['datatype.result', '{"datatypes": {"DT_HVACVent": {"childs": [], "values": {"1": "Heat", "0": "Auto", "3": "Fan only", "2": "Cool", "4": "Dry"}}, "DT_DateTime": {"childs": ["DT_Date", "DT_Time"], "format": "YYYY-MM-DDThh:mm:ss.s"}, "DT_String": {"childs": ["DT_Phone", "DT_Hexa", "DT_ColorRGBHexa", "DT_CoordD", "DT_CoordDM", "DT_CoordDMS"], "maxLengh": null, "format": null}, "DT_CoordDM": {"childs": [], "parent": "DT_String", "format": "(N|S) DD MM.mmm,(E|W) DD MM.mmm"}, "DT_ColorCII": {"childs": [], "values": {"B": "Blue", "Br": "Brown", "G": "Green", "O": "Orange", "Bk": "Black", "R": "Red", "W": "White", "Y": "Yellow"}}, "DT_Time": {"childs": [], "parent": "DT_DateTime", "format": "hh:mm:ss.s"}, "DT_Start": {"childs": [], "labels": {"1": "Start", "0": "Stop"}, "parent": "DT_Bool"}, "DT_Char": {"childs": []}, "DT_CoordD": {"childs": [], "parent": "DT_String", "format": "DD.dddddd,DD.dddddd"}, "DT_Date": {"childs": [], "parent": "DT_DateTime", "format": "YYYY-MM-DD"}, "DT_mSecond": {"max": 999, "childs": [], "parent": "DT_Number", "unit": "ms", "min": 0}, "DT_ColorCMYK": {"childs": [], "parent": "DT_List", "format": "(C 0-100%),(M 0-100%),(Y 0-100%),(K 0-100%)"}, "DT_DayOfWeek": {"childs": [], "values": {"1": "Monday", "0": "no day", "3": "Wednesday", "2": "Tuesday", "5": "Friday", "4": "Thursday", "7": "Sunday", "6": "Saturday"}}, "DT_State": {"childs": [], "labels": {"1": "Active", "0": "Inactive"}, "parent": "DT_Bool"}, "DT_Trigger": {"childs": [], "labels": {"1": "Triggered"}}, "DT_MByte": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Mb", "min": null}, "DT_Month": {"max": 12, "childs": [], "parent": "DT_Number", "unit": "Month", "min": 1}, "DT_Angle": {"max": 360, "childs": [], "parent": "DT_Number", "unit": "\u00b0", "min": 0}, "DT_Step": {"childs": [], "labels": {"1": "Increase", "0": "Decrease"}, "parent": "DT_Bool"}, "DT_Enable": {"childs": [], "labels": {"1": "Enable", "0": "Disable"}, "parent": "DT_Bool"}, "DT_Chlorine": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mg/l", "min": null}, "DT_Bool": {"childs": ["DT_Switch", "DT_Enable", "DT_Binary", "DT_Step", "DT_UpDown", "DT_OpenClose", "DT_Start", "DT_State"], "labels": {"1": "True", "0": "False"}}, "DT_Hexa": {"childs": ["DT_ColorRGBHexa"], "parent": "DT_String", "maxLengh": null, "format": null}, "DT_ColorRGBHexa": {"childs": [], "parent": "DT_Hexa", "maxLengh": 6, "format": "RRGGBB"}, "DT_Scaling": {"max": 100, "childs": [], "parent": "DT_Number", "unit": "%", "min": 0}, "DT_kmhSpeed": {"max": null, "childs": [], "parent": "DT_Number", "unit": "km/h", "min": null}, "DT_mActiveEnergy": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mWh", "min": null}, "DT_Phone": {"childs": [], "parent": "DT_String", "maxLengh": null, "format": "+00000000000"}, "DT_kActiveEnergy": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kWh", "min": null}, "DT_kCurrent": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kA", "min": null}, "DT_List": {"childs": ["DT_ColorRGB", "DT_ColorCMYK"], "format": null}, "DT_Volt": {"max": null, "childs": [], "parent": "DT_Number", "unit": "V", "min": null}, "DT_Minute": {"max": 59, "childs": [], "parent": "DT_Number", "unit": "min", "min": 0}, "DT_OpenClose": {"childs": [], "labels": {"1": "Close", "0": "Open"}, "parent": "DT_Bool"}, "DT_Switch": {"childs": [], "labels": {"1": "On", "0": "Off"}, "parent": "DT_Bool"}, "DT_ColorRGB": {"childs": [], "parent": "DT_List", "format": "(R 0-255),(G 0-255),(B 0-255)"}, "DT_ActiveEnergy": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Wh", "min": null}, "DT_AirQuality": {"max": null, "childs": [], "parent": "DT_Number", "unit": "ppm", "min": null}, "DT_UPSEvent": {"childs": [], "values": {"input_voltage_ok": "Input voltage returns ok", "temp_ok": "UPS temperature returns ok", "output_overload": "UPS output overload", "comms_ok": "UPS communication restored", "btp": "Battery test passed", "output_voltage_ok": "UPS Output voltage returns ok", "battlow": "Battery is low", "comms_lost": "Host lost UPS communication", "output_ok": "UPS output returns ok", "battfull": "Battery is fully charged", "output_voltage_high": "UPS Output voltage too high", "btf": "Battery test failed", "temp_high": "UPS temperature too high", "input_freq_error": "Input frequency out of range", "input_freq_ok": "Input frequency returns ok", "onmains": "Mains power", "input_voltage_low": "Input voltage too low", "output_voltage_low": "UPS Output voltage too low", "bti": "Battery test initiated", "input_voltage_high": "Input voltage too high", "onbattery": "Battery power"}}, "DT_Humidity": {"max": null, "childs": [], "parent": "DT_Number", "unit": "%", "min": null}, "DT_Timestamp": {"max": null, "childs": [], "parent": "DT_Number", "unit": null, "min": null}, "DT_Binary": {"childs": [], "labels": {"1": "High", "0": "Low"}, "parent": "DT_Bool"}, "DT_mCurrent": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mA", "min": null}, "DT_pH": {"max": null, "childs": [], "parent": "DT_Number", "unit": "pH", "min": null}, "DT_Year": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Year", "min": null}, "DT_Hour": {"max": 23, "childs": [], "parent": "DT_Number", "unit": "h", "min": 0}, "DT_Second": {"max": 59, "childs": [], "parent": "DT_Number", "unit": "s", "min": 0}, "DT_Number": {"max": null, "childs": ["DT_Scaling", "DT_Angle", "DT_Brightness", "DT_Temp", "DT_TempK", "DT_TempF", "DT_Pression", "DT_Humidity", "DT_AirQuality", "DT_Volt", "DT_mVolt", "DT_kVolt", "DT_Current", "DT_mCurrent", "DT_kCurrent", "DT_Power", "DT_mPower", "DT_kPower", "DT_ActiveEnergy", "DT_kActiveEnergy", "DT_ApparantEnergy", "DT_Speed", "DT_kmhSpeed", "DT_Year", "DT_Month", "DT_Day", "DT_Hour", "DT_Minute", "DT_Second", "DT_mSecond", "DT_Timestamp", "DT_mMeter", "DT_mMeterHour", "DT_Byte", "DT_kByte", "DT_MByte", "DT_GByte", "DT_pH", "DT_Chlorine", "DT_Battery"], "unit": null, "min": null}, "DT_Speed": {"max": null, "childs": [], "parent": "DT_Number", "unit": "m/s", "min": null}, "DT_Day": {"max": 31, "childs": [], "parent": "DT_Number", "unit": "Day", "min": 1}, "DT_HVACFan": {"childs": [], "values": {"1": "Auto", "0": "Unknown", "3": "Speed 1", "2": "Lower", "5": "Speed 3", "4": "Speed 2", "7": "Speed 5", "6": "Speed 4"}}, "DT_mMeter": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mm", "min": null}, "DT_mMeterHour": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mm/h", "min": null}, "DT_Pression": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Pa", "min": null}, "DT_Battery": {"max": 100, "childs": [], "parent": "DT_Number", "unit": "%", "min": 0}, "DT_mPower": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mW", "min": null}, "DT_Current": {"max": null, "childs": [], "parent": "DT_Number", "unit": "A", "min": null}, "DT_ApparantEnergy": {"max": null, "childs": [], "parent": "DT_Number", "unit": "VAh", "min": null}, "DT_CoordDMS": {"childs": [], "parent": "DT_String", "format": "(N|S) DD MM SS.s,(E|W) DD MM SS.s"}, "DT_kByte": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kb", "min": null}, "DT_Power": {"max": null, "childs": [], "parent": "DT_Number", "unit": "W", "min": null}, "DT_kVolt": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kV", "min": null}, "DT_GByte": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Gb", "min": null}, "DT_HVACMode": {"childs": [], "values": {"1": "Comfort", "0": "Auto", "3": "Economy", "2": "Standby", "4": "Building Protection"}}, "DT_kPower": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kW", "min": null}, "DT_Byte": {"max": null, "childs": [], "parent": "DT_Number", "unit": "b", "min": null}, "DT_Brightness": {"max": null, "childs": [], "parent": "DT_Number", "unit": "lux", "min": null}, "DT_TempK": {"max": null, "childs": [], "parent": "DT_Number", "unit": "K", "min": null}, "DT_mVolt": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mV", "min": null}, "DT_TempF": {"max": null, "childs": [], "parent": "DT_Number", "unit": "\u00b0F", "min": null}, "DT_Temp": {"max": null, "childs": [], "parent": "DT_Number", "unit": "\u00b0C", "min": null}, "DT_HVACHeat": {"childs": [], "values": {"1": "Comfort", "0": "Auto", "3": "Economy", "2": "Standby", "4": "Building Protection"}}, "DT_UpDown": {"childs": [], "labels": {"1": "Down", "0": "Up"}, "parent": "DT_Bool"}, "DT_UPSState": {"childs": [], "values": {"OL": "mains", "LB": "unknown", "OB": "battery"}}}}']
    2016-03-01 16:41:47,682 domogik-mq_broker INFO A worker seems to be dead : wid=^@k<8B>F0 service=admin
    2016-03-01 16:41:47,682 domogik-mq_broker DEBUG Try to unregister a worker : wid=^@k<8B>F0
    2016-03-01 16:41:47,682 domogik-mq_broker INFO Unregistered worker : wid=^@k<8B>F0
    2016-03-01 16:42:04,668 domogik-mq_broker DEBUG Client REQ received: to='dbmgr' data=['sensor_history.get', '{"sensor_id": 93, "mode": "last"}']
    2016-03-01 16:42:04,672 domogik-mq_broker DEBUG WORKER REP received: from='dbmgr' data=['sensor_history.result', '{"status": true, "reason": "", "sensor_id": 93, "values": [{"timestamp": 1456846088, "value_str": "-9", "value_num": -9.0}], "mode": "last"}']
    2016-03-01 16:42:13,993 domogik-mq_broker DEBUG Try to register a worker : wid=^@k<8B>F<96>, service=admin
    2016-03-01 16:42:13,994 domogik-mq_broker INFO Registered worker : wid=^@k<8B>F<96>, service=admin

**Comment by fritz-smh** [comment] 2016-03-06 22:53
Do you still got the issue ?
I ma not able to reproduce it with the last pulls

**Comment by vdomos** [comment] 2016-03-06 23:49
yes still there.
I update now on the VM with the last pull, restart Domogik and the timeline is still very long.

    2016-03-07 00:38:41,030 domogik.admin.application INFO http request for /timeline/ received
    2016-03-07 00:38:41,735 domogik-admin DEBUG Send client status : alive
    2016-03-07 00:38:56,905 domogik-admin DEBUG Send client status : alive
    2016-03-07 00:39:12,028 domogik-admin DEBUG Send client status : alive
    2016-03-07 00:39:27,128 domogik-admin DEBUG Send client status : alive
    2016-03-07 00:39:30,818 domogik.admin.application DEBUG  => response status code: 200
    2016-03-07 00:39:30,818 domogik.admin.application DEBUG  => response content_type: text/html; charset=utf-8

The VM is not overloaded

    $ uptime
     00:42:12 up 10 days, 10:46,  3 users,  load average: 0,51, 0,62, 0,62

**Comment by vdomos** [comment] 2016-03-07 00:34
I do the same udpate and restart on the RPI2, and now the timeline is displayed quickly.
The VM and RPI2 have the same devices.

I don't understand !

**Comment by fritz-smh** [comment] 2016-03-07 08:37
do they use the same database ?

can you do on both a :
select count(*) from core_sensor_history

**Comment by vdomos** [comment] 2016-03-07 10:01
The vm and rpi2 uses a different database. 
The device created are identical ( same acces to onewire bus, same sensor script execute, same vdevice, weather, mqtt and xpl rfxcom sensors, only callerid is on rpi2)
The vm runs longer than the rpi2 the sensor_history is more consistent.
Vm: 590354
rpi2: 282395

I have  the same response time for timeline with rpi2 but the last update has seems to have solved the problem.
but not for vm.

With the #233 on th Vm too, maybe I should do a complete reinstallation of Domogik.

**Comment by fritz-smh** [comment] 2016-04-11 17:31
Closing for now...

**Closed by fritz-smh** 2016-04-11 17:31 UTC
Labels: bug
