### ISSUE TITLE
Problems when I want download a dmg package on Rasp Pi B 512 MB

### ISSUE THREAD

**Issue by TheGrumpy** [domogik/domogik#130] opened 2015-10-13 19:45 UTC
After a standard installation on a raspberry pi b 512MB, installation OK, I want to install a package with the command line (for exemple :  dmg_package --install http://github.com/fritz-smh/domogik-plugin-weather/archive/1.2.zip )
 And the result is :

Start downloading http://github.com/fritz-smh/domogik-plugin-weather/archive/1.2.zip
Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
ZeroReturnError

Download finished
Traceback (most recent call last):
  File "/usr/local/bin/dmg_package", line 9, in <module>
    load_entry_point('Domogik==0.4.0', 'console_scripts', 'dmg_package')()
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 587, in main
    pkg = PackageInstaller()
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 126, in __init__
    self.install(self.options.install)
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 167, in install
    downloaded_file, mime = self.download_from_url(package)
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 402, in download_from_url
    return downloaded_file, mime
UnboundLocalError: local variable 'mime' referenced before assignment

It's exactly the same things with other packages

**Comment by fritz-smh** [comment] 2015-10-13 20:04
Hi, this is a duplicate of https://github.com/domogik/domogik/issues/99

I close it for now as it may be resolved. Please feel free to open it if you still encounter it in 0.4.2 when it will be released.

**Closed by fritz-smh** 2015-10-13 20:04 UTC
Labels: bug

**Comment by TheGrumpy** [comment] 2015-10-13 20:24
You ask me on twitter to open a ticket for this problem !! I open a ticket ... :-)

**Comment by fritz-smh** [comment] 2015-10-13 20:34
yes, I was not sure it was the same issue, and I was curious to see if it was the case...
