### ISSUE TITLE
XPL error (python version) dmg_hub not in path

### ISSUE THREAD

**Issue by BytesBurner** [domogik/domogik#322] opened 2016-07-19 19:17 UTC
I have installed Domogik-mq & Domogik in a Debian 7 system. Not Domogik user added, instead I used a preexisting user in the system. MySql database has also ready to use for this system user with passwd and granted privileges. All installed on python 2.7.3
Correctly added to init.d
Correctly running while from console $sudo /etc/init.d domogik start
But while reboot system an error is show: XPL Error (python version) dmg_hub not in path
Domogik does not start
Well, when open domogik ($sudo nano /etc/init.d/domogik it can see that
_____
DOMOGIK_XPL_HUB="python"
PYTHON_XPLHUB=dmg_hub
.
.
.
elif [ "${DOMOGIK_XPL_HUB}" == "python" ] ; then
        if [ -z "$(which ${PYTHON_XPLHUB})" ];then
            echo "ERROR : ${PYTHON_XPLHUB} not in path, did you had any issue during the installation ?"
            exit 1
        fi
        /bin/su - ${DOMOGIK_USER} -c "$(which ${PYTHON_XPLHUB}) >/dev/null"
        if [ $? -gt 0 ]; then
            echo " An error occured during Xpl startup."
            exit 1
        fi

____________
Well, dmg_hub exists but line  if [ -z "$(which ${PYTHON_XPLHUB})" ] in domogik at init does not find it.
In fact, I created a sh script whit just above lines and it doesn´t exit 1

**Comment by fritz-smh** [comment] 2016-09-15 12:08
Hi,

Sorry to be so late to comment on the ticket. It was lost in deeper space :(

I think the issue is solved since this commit :

commit 1b8881b4640b460b9eef4b485249a2a885a593d3
Author: Fritz <fritz.smh@gmail.com>
Date:   Thu Aug 4 16:40:04 2016 +0200
Fix init : missing PATH

Could you please check ?

Thanks and sorry,
Fritz

**Comment by fritz-smh** [comment] 2016-09-15 14:14
Closing for now

**Closed by fritz-smh** 2016-09-15 14:14 UTC
Labels: bug
